### ISSUE TITLE
Add keybinding for reselecting Roblox UWP app window

### ISSUE THREAD

**Issue by Sheep-s4n** [mengdeveloper/microsoftrbx-cursor-fix#43]
Currently, there is no way to quickly reselect the Roblox UWP app window after closing it and opening a new window. The user needs to close the program and open it again to perform this action.
Therefore, adding a keybind to quickly reselect a new Roblox window would be great for UX.

**Comment by keplerHaloxx** [comment]
made a pr [here](https://github.com/mengdeveloper/microsoftrbx-cursor-fix/pull/45)

**Comment by Sheep-s4n** [comment]
ok, thank you very much.
