### ISSUE TITLE
Issue with the border lock with mouse location 

### ISSUE THREAD

**Issue by Zxvnzz** [mengdeveloper/microsoftrbx-cursor-fix#44]
THe new 3rd input is very nice and i've wanted for along time, and im happy it was added. However, when Im playing games that are first person like arsenal its common foe me to look up and down, but when I go to the top right corner the close button for roblox appears and when I have to shoot, I click LMB so when I aim at the top right corner and click LMB it closes roblox.

**Comment by Zxvnzz** [comment]
Please fix soon!!!

**Comment by Sheep-s4n** [comment]
Just use the first option (force central lock) to play the arsenal. This works fine for me.

**Comment by zzahkaboom24** [comment]
I already fixed it, but the fix hasnt been merged yet @Zxvnzz @Sheep-s4n
Here is the PR -> #32 & #38 
Here is the binary, if you don't want to compile it yourself:
32Bit -> [x32.CursorFix.V1.0.9.zip](https://github.com/mengdeveloper/microsoftrbx-cursor-fix/files/13222430/x32.CursorFix.V1.0.9.zip)
64Bit -> [x64.CursorFix.V1.0.9.zip](https://github.com/mengdeveloper/microsoftrbx-cursor-fix/files/13222431/x64.CursorFix.V1.0.9.zip)
